# Generated by Django 4.2.2 on 2023-08-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "production_year",
                    models.PositiveIntegerField(verbose_name="Год производства"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                ("director", models.CharField(max_length=255, verbose_name="Режиссер")),
                (
                    "film_duration",
                    models.TimeField(verbose_name="Продолжительность фильма"),
                ),
                ("plot", models.TextField(verbose_name="Сюжет")),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="Рейтинг"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Публикация"),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
                "ordering": ["-time_create", "title"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Напишите свой отзыв",
                        max_length=1000,
                        verbose_name="Рецензия",
                    ),
                ),
                (
                    "mark",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=(5, "5"),
                        help_text="Поставьте оценку",
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="film.film",
                        to_field="title",
                        verbose_name="Фильм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецензия",
                "verbose_name_plural": "Рецензии",
                "ordering": ["user_name", "film_id"],
                "unique_together": {("user_name", "film_id")},
            },
        ),
    ]
